pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'PaperMC'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'svl-bridge'

include 'common'
include 'paper'
include 'fabric'
include 'neoforge'
include 'neoforge-1.20.4'
include 'forge'
include 'forge-1.20.1'
