plugins {
    id 'java'
}

base {
    archivesName = 'svl-bridge-neoforge-1.20.4'
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    implementation project(':common')
    compileOnly "net.neoforged:neoforge:20.4.237:universal"
    compileOnly "net.neoforged.fancymodloader:loader:2.0.21"
    compileOnly "net.neoforged:bus:7.2.0"
    compileOnly "org.slf4j:slf4j-api:2.0.13"
}

jar {
    from project(':common').sourceSets.main.output
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}
