plugins {
    id 'java'
}

base {
    archivesName = 'svl-bridge-neoforge'
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    implementation project(':common')
    compileOnly "net.neoforged:neoforge:${project.neoforge_version}:universal"
    compileOnly "net.neoforged.fancymodloader:loader:4.0.24"
    compileOnly "net.neoforged:bus:8.0.2"
    compileOnly "org.slf4j:slf4j-api:2.0.13"
}

jar {
    from project(':common').sourceSets.main.output
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}
